# in utils.py, nella funzione def get_coreset_idx_randomp()
# il ciclo for _ in tqdm(range(n-1), **get_tqdm_params()):
#non dava errore